/// Flutter icons Custom2
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom2
///      fonts:
///       - asset: fonts/Custom2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom2 {
  Custom2._();

  static const _kFontFam = 'Custom2';
  static const _kFontPkg = null;

  static const IconData iconberi = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconminta = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconbox = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
