/// Flutter icons Custom1
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom1
///      fonts:
///       - asset: fonts/Custom1.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom1 {
  Custom1._();

  static const _kFontFam = 'Custom1';
  static const _kFontPkg = null;

  static const IconData iconpoint = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icontopup = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
